FROM ubuntu
MAINTAINER Han SangGu <sghan@hinetworks.kr>

RUN apt-get update
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN groupadd -r admin && useradd -r -g admin admin
RUN echo "admin:unl" | chpasswd

CMD ["/usr/sbin/sshd", "-D"]

EXPOSE 22

