FROM ubuntu
MAINTAINER Han SangGu <sghan@hinetworks.kr>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN echo "mysql-server mysql-server/root_password password unl123" | debconf-set-selections
RUN echo "mysql-server mysql-server/root_password_again password unl123" | debconf-set-selections
RUN apt-get install -y mysql-server

WORKDIR /etc/mysql/mysql.conf.d
RUN sed -i "s/127.0.0.1/0.0.0.0/g" mysqld.cnf

RUN mkdir /var/run/mysqld
RUN chown mysql.mysql /var/run/mysqld

CMD ["/usr/sbin/mysqld"]

EXPOSE 3306
